#!/usr/bin/env bash
#
# SANVIL SYSTEM CONFIGURATOR v1.0.0
# Copyright (c) 2025 Sanvil
# Configure bash profile and vim settings for Debian 12 server
#
# Usage: ./4_system_customization.sh <HOST> [user] [port]

set -euo pipefail

HOST="${1:-}"
USER="${2:-debian}"
PORT="${3:-22}"

if [[ -z "${HOST}" ]]; then
  echo "SANVIL SYSTEM CONFIGURATOR v1.0.0"
  echo "Usage: $0 <HOST> [user] [port]"
  echo "Example: $0 example.org debian 22"
  exit 1
fi

SSH_OPTS="-o StrictHostKeyChecking=accept-new -o PreferredAuthentications=keyboard-interactive,password,publickey -o PubkeyAuthentication=yes"

echo "SANVIL SYSTEM CONFIGURATOR - ${HOST}"
echo "User: ${USER} | Port: ${PORT}"
echo "Configurations to apply:"
echo "  - Custom bash profile"
echo "  - Advanced Vim configuration"
echo

echo "STEP 1 — System configuration"

read -r -p "Press ENTER to start configuration..."

ssh -tt ${SSH_OPTS} -p "${PORT}" "${USER}@${HOST}" 'sudo bash -c "
echo \"=== Bash Profile Configuration ===\"

# Backup existing file if present
if [ -f ~/.bash_profile ]; then
  cp ~/.bash_profile ~/.bash_profile.backup.$(date +%Y%m%d_%H%M%S)
  echo \"✅ Bash profile backup created\"
fi

# Create new bash_profile
cat > ~/.bash_profile << \"EOF\"
# SANVIL BASH PROFILE CONFIGURATION
# Generated by SANVIL SYSTEM CONFIGURATOR

# Custom colorized prompt
export PS1=\"\\[\\033[36m\\]\\u\\[\\033[m\\]@\\[\\033[32m\\]\\h:\\[\\033[33;1m\\]\\w\\[\\033[m\\]\\$ \"

# Color configuration
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Useful aliases for server administration
alias nmaps=\"sudo nmap -PN -sS -f -vv -n -T4 --max-rtt-timeout 15 \"
alias lsa=\"ls -al\"
alias ls=\"ls -GFh\"
alias psa=\"ps aux | more\"
alias psg=\"ps aux | grep\"
alias search=\"find / -name\"
alias wget=\"wget -c\"

# Additional productivity aliases
alias ll=\"ls -la\"
alias la=\"ls -A\"
alias l=\"ls -CF\"
alias ..=\"cd ..\"
alias ...=\"cd ../..\"
alias grep=\"grep --color=auto\"
alias fgrep=\"fgrep --color=auto\"
alias egrep=\"egrep --color=auto\"

# History configuration
export HISTSIZE=10000
export HISTFILESIZE=20000
export HISTCONTROL=ignoredups:erasedups

# Load additional configurations if present
if [ -f ~/.bashrc ]; then
    source ~/.bashrc
fi

echo \"SANVIL bash profile loaded - $(date)\"
EOF

echo \"✅ Bash profile configured\"

echo \"=== Vim Configuration ===\"

# Backup existing file if present
if [ -f ~/.vimrc ]; then
  cp ~/.vimrc ~/.vimrc.backup.$(date +%Y%m%d_%H%M%S)
  echo \"✅ Vim configuration backup created\"
fi

# Create advanced vim configuration
{
echo \"\\\" SANVIL VIM CONFIGURATION\"
echo \"\\\" Generated by SANVIL SYSTEM CONFIGURATOR\"
echo \"\"
echo \"\\\" === DISPLAY SETTINGS ===\"
echo \"set number\"
echo \"syntax on\"
echo \"set showmatch\"
echo \"set showmode\"
echo \"set laststatus=2\"
echo \"set colorcolumn=80\"
echo \"set background=dark\"
echo \"colorscheme desert\"
echo \"\"
echo \"\\\" === EDITING SETTINGS ===\"
echo \"set mouse=a\"
echo \"set autoindent\"
echo \"set smartindent\"
echo \"set list\"
echo \"set listchars=tab:>-,trail:·\"
echo \"set tabstop=4\"
echo \"set shiftwidth=4\"
echo \"set expandtab\"
echo \"\"
echo \"\\\" === SEARCH SETTINGS ===\"
echo \"set incsearch\"
echo \"set ignorecase\"
echo \"set smartcase\"
echo \"set hlsearch\"
echo \"\"
echo \"\\\" === HISTORY AND BACKUP ===\"
echo \"set history=100\"
echo \"set nobackup\"
echo \"set nowritebackup\"
echo \"set noswapfile\"
echo \"\"
echo \"\\\" === PERFORMANCE ===\"
echo \"set ttyfast\"
echo \"set updatetime=250\"
echo \"\"
echo \"\\\" === AUTO COMMANDS ===\"
echo \"autocmd BufWritePre * :%s/\\\\s\\\\+\\\$//e\"
} > ~/.vimrc

echo \"✅ Vim configuration completed\"

echo \"=== Applying configurations ===\"

# Apply bash profile immediately
source ~/.bash_profile 2>/dev/null || echo \"Bash profile will be active on next login\"

echo \"✅ Configurations applied\"

echo \"=== Configuration verification ===\"

# Verify bash_profile
if [ -f ~/.bash_profile ]; then
  echo \"✅ Bash profile: configured ($(wc -l < ~/.bash_profile) lines)\"
else
  echo \"❌ Bash profile: ERROR\"
fi

# Verify vimrc
if [ -f ~/.vimrc ]; then
  echo \"✅ Vim config: configured ($(wc -l < ~/.vimrc) lines)\"
else
  echo \"❌ Vim config: ERROR\"
fi

echo \"=== Configuration testing ===\"
echo \"📊 Active configurations:\"
echo \"  Bash profile: ~/.bash_profile\"
echo \"  Vim config: ~/.vimrc\"
echo \"  Backup files: ~/.*.backup.*\"
"'

echo
echo "✅ SYSTEM CONFIGURATION COMPLETED"
echo "Applied configurations:"
echo "  - Custom bash profile with colorized prompt"
echo "  - Useful aliases for server administration"
echo "  - Advanced Vim configuration with syntax highlighting"
echo "  - Automatic backup of existing files"
echo
echo "💡 Configurations will be active on next SSH login"
echo
echo "© 2025 Sanvil"

exit 0
